const std = @import("std");
const gitweb = @import("gitweb.zig");
const main = @import("main.zig");
const git = @import("git.zig");

pub fn writeHeader(ctx: *gitweb.Context, writer: anytype) !void {
    if (ctx.cfg.noheader) {
        return;
    }

    try writer.writeAll("<!DOCTYPE html>\n");
    try writer.writeAll("<html lang='en'>\n");
    try writer.writeAll("<head>\n");
    try writer.print("<meta charset='{s}'/>\n", .{ctx.page.charset});
    try writer.print("<title>{s}</title>\n", .{ctx.page.title});
    try writer.print("<link rel='stylesheet' type='text/css' href='{s}'/>\n", .{ctx.cfg.css});

    if (ctx.cfg.favicon.len > 0) {
        try writer.print("<link rel='shortcut icon' href='{s}'/>\n", .{ctx.cfg.favicon});
    }

    if (ctx.cfg.head_include) |include| {
        try includeFile(writer, include);
    }

    try writer.writeAll("</head>\n");
    try writer.writeAll("<body>\n");

    // Header section
    try writer.writeAll("<div id='gitweb'>\n");
    try writer.writeAll("<table id='header'>\n");
    try writer.writeAll("<tr>\n");
    try writer.writeAll("<td class='logo' rowspan='2'>");
    try writer.print("<a href='{s}'><img src='{s}' alt='gitweb logo'/></a>", .{ ctx.cfg.logo_link, ctx.cfg.logo });
    try writer.writeAll("</td>\n");
    try writer.print("<td class='main'><a href='{s}'>{s}</a></td>", .{ ctx.cfg.virtual_root, ctx.cfg.root_title });
    try writer.writeAll("</tr>\n");
    try writer.writeAll("<tr><td class='sub'>");
    try writer.writeAll(ctx.cfg.root_desc);
    try writer.writeAll("</td></tr>\n");
    try writer.writeAll("</table>\n");

    // Navigation tabs and branch selector
    if (ctx.repo) |repo| {
        try writeRepoTabs(ctx, repo, writer);
        try writeBranchSelector(ctx, repo, writer);
    }

    try writer.writeAll("<div class='content'>\n");
}

pub fn writeFooter(ctx: *gitweb.Context, writer: anytype) !void {
    if (ctx.cfg.noheader) {
        return;
    }

    try writer.writeAll("</div> <!-- class=content -->\n");

    if (ctx.cfg.footer) |footer| {
        try writer.writeAll("<div class='footer'>");
        try includeFile(writer, footer);
        try writer.writeAll("</div>\n");
    } else {
        try writer.writeAll("<div class='footer'>generated by ");
        try writer.print("<a href='https://github.com/mrjbq7/zig-gitweb'>zig-gitweb {s}</a>", .{main.version});
        try writer.writeAll(" at ");
        const timestamp = std.time.timestamp();
        try writer.print("{d}", .{timestamp});
        try writer.writeAll("</div>\n");
    }

    try writer.writeAll("</div> <!-- id=gitweb -->\n");
    try writer.writeAll("</body>\n");
    try writer.writeAll("</html>\n");
}

fn writeRepoTabs(ctx: *gitweb.Context, repo: *gitweb.Repo, writer: anytype) !void {
    try writer.writeAll("<table class='tabs'><tr><td>\n");

    const current_branch = ctx.query.get("h");

    // Summary tab
    try writeTab(writer, "summary", "summary", ctx.cmd, repo.name, current_branch);

    // Refs tab
    try writeTab(writer, "refs", "refs", ctx.cmd, repo.name, current_branch);

    // Log tab
    try writeTab(writer, "log", "log", ctx.cmd, repo.name, current_branch);

    // Tree tab
    try writeTab(writer, "tree", "tree", ctx.cmd, repo.name, current_branch);

    // Commit tab
    try writeTab(writer, "commit", "commit", ctx.cmd, repo.name, current_branch);

    // Diff tab
    try writeTab(writer, "diff", "diff", ctx.cmd, repo.name, current_branch);

    // Stats tab
    if (repo.max_stats != null) {
        try writeTab(writer, "stats", "stats", ctx.cmd, repo.name, current_branch);
    }

    try writer.writeAll("</td></tr></table>\n");
}

fn writeTab(writer: anytype, name: []const u8, cmd: []const u8, current_cmd: []const u8, repo_name: []const u8, branch: ?[]const u8) !void {
    if (std.mem.eql(u8, cmd, current_cmd)) {
        try writer.print("<a class='active' href='?r={s}&cmd={s}", .{ repo_name, cmd });
        if (branch) |b| {
            try writer.print("&h={s}", .{b});
        }
        try writer.print("'>{s}</a>", .{name});
    } else {
        try writer.print("<a href='?r={s}&cmd={s}", .{ repo_name, cmd });
        if (branch) |b| {
            try writer.print("&h={s}", .{b});
        }
        try writer.print("'>{s}</a>", .{name});
    }
}

fn writeBranchSelector(ctx: *gitweb.Context, repo: *gitweb.Repo, writer: anytype) !void {
    try writer.writeAll("<div class='branch-selector'>\n");
    try writer.writeAll("<form method='get' action=''>\n");

    // Include hidden fields for current parameters
    try writer.print("<input type='hidden' name='r' value='{s}' />\n", .{repo.name});
    if (ctx.cmd.len > 0) {
        try writer.print("<input type='hidden' name='cmd' value='{s}' />\n", .{ctx.cmd});
    }

    // Get current branch from query or use HEAD
    const current_branch = ctx.query.get("h") orelse "HEAD";

    try writer.writeAll("<label for='branch-select'>Branch: </label>\n");
    try writer.writeAll("<select name='h' id='branch-select' onchange='this.form.submit()'>\n");

    // Open repository to get branches
    var git_repo = git.Repository.open(repo.path) catch {
        try writer.writeAll("<option value='HEAD'>HEAD</option>\n");
        try writer.writeAll("</select>\n");
        try writer.writeAll("</form>\n");
        try writer.writeAll("</div>\n");
        return;
    };
    defer git_repo.close();

    // Add HEAD option
    if (std.mem.eql(u8, current_branch, "HEAD")) {
        try writer.writeAll("<option value='HEAD' selected>HEAD</option>\n");
    } else {
        try writer.writeAll("<option value='HEAD'>HEAD</option>\n");
    }

    // Get and list branches
    const branches = git_repo.getBranches(ctx.allocator) catch {
        try writer.writeAll("</select>\n");
        try writer.writeAll("</form>\n");
        try writer.writeAll("</div>\n");
        return;
    };
    defer ctx.allocator.free(branches);

    for (branches) |branch| {
        if (!branch.is_remote) {
            defer @constCast(&branch.ref).free();

            if (std.mem.eql(u8, current_branch, branch.name)) {
                try writer.print("<option value='{s}' selected>{s}</option>\n", .{ branch.name, branch.name });
            } else {
                try writer.print("<option value='{s}'>{s}</option>\n", .{ branch.name, branch.name });
            }
        }
    }

    try writer.writeAll("</select>\n");
    try writer.writeAll("<noscript><input type='submit' value='Switch' /></noscript>\n");
    try writer.writeAll("</form>\n");
    try writer.writeAll("</div>\n");
}

fn includeFile(writer: anytype, path: []const u8) !void {
    const file = std.fs.openFileAbsolute(path, .{}) catch {
        return; // Silently fail if include file doesn't exist
    };
    defer file.close();

    const content = file.readToEndAlloc(std.heap.page_allocator, std.math.maxInt(usize)) catch {
        return;
    };
    defer std.heap.page_allocator.free(content);

    try writer.writeAll(content);
}

pub fn htmlEscape(writer: anytype, text: []const u8) !void {
    for (text) |char| {
        switch (char) {
            '<' => try writer.writeAll("&lt;"),
            '>' => try writer.writeAll("&gt;"),
            '&' => try writer.writeAll("&amp;"),
            '"' => try writer.writeAll("&quot;"),
            '\'' => try writer.writeAll("&#39;"),
            else => try writer.writeByte(char),
        }
    }
}

pub fn urlEncode(writer: anytype, text: []const u8) !void {
    for (text) |char| {
        if (std.ascii.isAlphanumeric(char) or char == '-' or char == '_' or char == '.' or char == '~') {
            try writer.writeByte(char);
        } else {
            try writer.print("%{X:0>2}", .{char});
        }
    }
}

pub fn writeLink(writer: anytype, url: []const u8, text: []const u8) !void {
    try writer.print("<a href='{s}'>", .{url});
    try htmlEscape(writer, text);
    try writer.writeAll("</a>");
}

pub fn writeTableHeader(writer: anytype, headers: []const []const u8) !void {
    try writer.writeAll("<table class='list'>\n");
    try writer.writeAll("<tr class='nohover'>");
    for (headers) |header| {
        try writer.print("<th>{s}</th>", .{header});
    }
    try writer.writeAll("</tr>\n");
}

pub fn writeTableRow(writer: anytype, class: ?[]const u8) !void {
    if (class) |c| {
        try writer.print("<tr class='{s}'>", .{c});
    } else {
        try writer.writeAll("<tr>");
    }
}

pub fn writeTableCell(writer: anytype, class: ?[]const u8, content: []const u8) !void {
    if (class) |c| {
        try writer.print("<td class='{s}'>", .{c});
    } else {
        try writer.writeAll("<td>");
    }
    try htmlEscape(writer, content);
    try writer.writeAll("</td>");
}

pub fn writeTableFooter(writer: anytype) !void {
    try writer.writeAll("</table>\n");
}
